spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasklist_db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080