version: "3.9"
services:
  postgres:
    image: postgres:15.2
    container_name: tasklist_db
    environment:
      POSTGRES_DB: tasklist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"